### ISSUE TITLE
TestRouting8

### ISSUE THREAD

**Issue by nishanths** [go-web-framework/gflux#1]
Previously `TestRouting8` wasn't failing because the Handle method in `mux.go` was handling errors [incorrectly](https://github.com/go-web-framework/gflux/blob/60642ae055a01615c6aa97ba4d73e256110b96c6/mux/mux.go#L31:L32). We should have been returning err, not nil.

```
if err != nil {
	return nil
}
```

The test failure log is below:

```
--- FAIL: TestRouting8 (0.00s)
panic: managed to get a query with no forward slash [recovered]
	panic: managed to get a query with no forward slash

goroutine 20 [running]:
panic(0x2358e0, 0xc4200d41a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc42008ac00)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x2358e0, 0xc4200d41a0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/go-web-framework/gflux/mux.(*Mux).Handle(0xc42004df40, 0x2810bc, 0xa, 0x0, 0x0, 0x0, 0x382b60, 0xc4200d4160, 0xc4200d2a00)
	/Users/nishanthshanmugham/go/src/github.com/go-web-framework/gflux/mux/mux.go:45 +0x123
github.com/go-web-framework/gflux/mux.TestRouting8(0xc42008ac00)
	/Users/nishanthshanmugham/go/src/github.com/go-web-framework/gflux/mux/mux_test.go:350 +0x24d
testing.tRunner(0xc42008ac00, 0x2a0778)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
exit status 2
FAIL	github.com/go-web-framework/gflux/mux	0.015s
```

The related lines in `bs_radix.go` are https://github.com/go-web-framework/gflux/blob/d3d98d4/mux/bs_radix.go#L161:L167

**Comment by nishanths** [comment]
@SaltedCashew when you find time :)

**Comment by nishanths** [comment]
Was reading the test wrong. Fixed the test to check for panic, instead of route being `nil`. diff: https://github.com/go-web-framework/gflux/commit/abd4d0760fb7e7f0cc39ee2e80118ed3823b8703
